In [15]:
import numpy as np
import pandas as pd
import sklearn
import random
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold

In [2]:
iris = load_iris()
print(iris.keys())
print(iris.data[0:3,:],'\n\n',iris.target)
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data,train_label)
pred = dt_clf.predict(train_data)
print(accuracy_score(train_label,pred))


dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]] 

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
1.0


In [3]:
iris_data = load_iris()
dt_clf = DecisionTreeClassifier()
x_train,x_test,y_train,y_test = train_test_split(iris_data.data,iris_data.target,test_size=0.3,random_state=121)
dt_clf.fit(x_train,y_train)
pred=dt_clf.predict(x_test)
accuracy_score(y_test,pred)

0.9555555555555556

In [142]:
# 5 fold cross validation

features = iris.data
label = iris.target

dt_clf = DecisionTreeClassifier(random_state=156)


###CV
kfold = KFold(n_splits=5,shuffle=False)

n_iter = 0
cv_accuracy = []
for train_index, test_index in kfold.split(features):
    x_train, x_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    dt_clf.fit(x_train,y_train)
    pred = dt_clf.predict(x_test)
    n_iter +=1
    accuracy = np.around(accuracy_score(pred,y_test),4)
    print('\n fold :',n_iter,'\n\n','정확도 :',accuracy,'\n','검증세트 인덱스 :',test_index)
    cv_accuracy.append(accuracy)
    
np.array(cv_accuracy).mean()


 fold : 1 

 정확도 : 1.0 
 검증세트 인덱스 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

 fold : 2 

 정확도 : 0.9667 
 검증세트 인덱스 : [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

 fold : 3 

 정확도 : 0.8667 
 검증세트 인덱스 : [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

 fold : 4 

 정확도 : 0.9333 
 검증세트 인덱스 : [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

 fold : 5 

 정확도 : 0.7333 
 검증세트 인덱스 : [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]


0.9